var testCases = {
	camelCase: [['Foo Bar'],['--foo-bar--'],['__FOO_BAR__']],
	capitalize: [['FRED']],
	deburr: [['déjà vu']],
	endsWith: [['abc', 'c'],['abc', 'b'],['abc', 'b', 2]],
	escape: [['fred, barney, & pebbles']],
	escapeRegExp: [['[lodash](https://lodash.com/)']],
	kebabCase: [['Foo Bar'],['fooBar'],['__FOO_BAR__']],
	lowerCase: [['--Foo-Bar--'],['fooBar'],['__FOO_BAR__']],
	lowerFirst: [['Fred'],['FRED']],
	pad: [['abc', 8],['abc', 8, '_-'],['abc', 3]],
	padEnd: [['abc', 6],['abc', 6, '_-'],['abc', 3]],
	padStart: [['abc', 6],['abc', 6, '_-'],['abc', 3]],
	parseInt: [['08']],
	repeat: [['*', 3],['abc', 2],['abc', 0]],
	replace: [['Hi Fred', 'Fred', 'Barney']],
	snakeCase: [['Foo Bar'],['fooBar'],['--FOO-BAR--']],
	split: [['a-b-c', '-', 2]],
	startCase: [['--foo-bar--'],['fooBar'],['__FOO_BAR__']],
}
